version: 2
jobs:
  build:
    working_directory: /health-check
    docker:
      - image: docker:17.12.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/health-check.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/health-check.tar | true
      - run:
          name: Build health-checklication Docker image
          command: |
            docker build --cache-from=health-check -t dlvrchris/health-check .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/health-check.tar health-check
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/health-check.tar
      - run:
          name: Run tests
          command: |
            docker-compose -f ./docker-compose.test.yml up
      - deploy:
          name: Push health-check Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push "dlvrchris/healthcheck"
            fi
