version: 2
jobs:
  build:
    working_directory: /health-check
    docker:
      - image: docker:17.12.1-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip
            pip install \
              docker-compose
      - run:
          name: Build application Docker image
          command: |
            docker build -t app .
      - deploy:
          name: Push app Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login --username dlvrchris --password $DOCKERHUBPW
              docker tag app "dlvrchris/healthcheck"
              docker push "dlvrchris/healthcheck"
            fi
